-- CREATE TABLE ACCOUNT

CREATE TABLE "ACCOUNT" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "USERNAME" VARCHAR2(100 BYTE) UNIQUE,
    "PASSWORD_HASH" VARCHAR2(255 BYTE),
    "PROFILE_PICTURE" CLOB,
    "EMAIL" VARCHAR2(100 BYTE) UNIQUE,
    "FIRST_NAME" VARCHAR2(100 BYTE),
    "LAST_NAME" VARCHAR2(100 BYTE),
    "ROLE" VARCHAR2(50 BYTE), -- e.g Admin, User, Moderator
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "LAST_LOGIN" TIMESTAMP
);

CREATE TABLE "USERS" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "ACOUNT_ID" VARCHAR2(100 BYTE) UNIQUE,
    "SINGLE_ID" VARCHAR2(255 BYTE) UNIQUE,
    "NICKNAME" VARCHAR2(100 BYTE),
    "IDENTIFICATION_NUMBER" VARCHAR2(100 BYTE) UNIQUE,
    "PHONE_NUMBER" VARCHAR2(20 BYTE),
    "ADDRESS" VARCHAR2(255 BYTE),
    "DATE_OF_BIRTH" TIMESTAMP,
    "EXPIRED_AT" TIMESTAMP,
    "STATUS" VARCHAR2(50 BYTE), -- e.g Active, Inactive, Banned
    "POINTS" NUMBER DEFAULT 0,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;