-- CREATE TABLE HISTORY_PURCHASE

CREATE TABLE "HISTORY_PURCHASE" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "SINGLE_ID" VARCHAR2(255 BYTE),
    "ACCOUNT_ID" VARCHAR2(255 BYTE),
    "SHOP_ITEM_ID" VARCHAR2(255 BYTE),
    "ITEM_NAME" VARCHAR2(255 BYTE),
    "ITEM_TYPE" VARCHAR2(100 BYTE), -- e.g Card, Booster Pack, Subscription
    "QUANTITY" NUMBER,
    "PRICE" NUMBER,
    "PURCHASE_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "PAYMENT_METHOD" VARCHAR2(100 BYTE), -- e.g Credit Card, PayPal, Gift Card
    "TRANSACTION_ID" VARCHAR2(255 BYTE) UNIQUE,
    "STATUS" VARCHAR2(50 BYTE), -- e.g Completed, Pending, Failed
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNT"("ID"),
    FOREIGN KEY ("SHOP_ITEM_ID") REFERENCES "SHOP_ITEMS"("ID"),
    FOREIGN KEY ("SINGLE_ID") REFERENCES "SINGLE"("ID")
);

COMMIT;