-- CREATE TABLE TOURNAMENT

CREATE TABLE "TOURNAMENT" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "PRIZE_ID" VARCHAR2(255 BYTE),
    "NAME" VARCHAR2(255 BYTE),
    "DESCRIPTION" CLOB,
    "START_DATE" TIMESTAMP,
    "END_DATE" TIMESTAMP,
    "LOCATION" VARCHAR2(255 BYTE),
    "ENTRY_FEE" NUMBER,
    "GAME_TITLE" VARCHAR2(255 BYTE),
    "ORGANIZER" VARCHAR2(100 BYTE),
    "RULES" CLOB,
    "REGISTRATION_DEADLINE" TIMESTAMP,
    "MAX_TEAMS" NUMBER,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PARTICIPANTS (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "TOURNAMENT_ID" VARCHAR2(255 BYTE),
    "ACCOUNT_ID" VARCHAR2(255 BYTE),
    "NICKNAME" VARCHAR2(100 BYTE),
    "TEAM_NAME" VARCHAR2(255 BYTE),
    "REGISTRATION_DATE" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("TOURNAMENT_ID") REFERENCES "TOURNAMENT"("ID"),
    FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNT"("ID")
);

COMMIT;