-- Account Sql

CREATE TABLE PERSONA (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) DEFAULT '+673',
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uq_persona_email (EMAIL),
    UNIQUE KEY uq_persona_phone (PHONE)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;


CREATE TABLE RESET (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PERSONA_ID INT UNSIGNED NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    USED TINYINT(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uq_reset_token (TOKEN),
    KEY idx_reset_persona (PERSONA_ID),
    CONSTRAINT fk_reset_persona
        FOREIGN KEY (PERSONA_ID)
        REFERENCES PERSONA(ID)
        ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
