CREATE TABLE PERSONAL_USER(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR (100),
EMAIL VARCHAR (100),
PHONE VARCHAR (15),
PASSWORD VARCHAR (100),
CONFIRM_PASSWORD VARCHAR (100),
PROFILE_ICON VARCHAR (255),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP
);

CREATE TABLE RESET_PASSWORD (
USER_ID INT,
ID INT, 
NEW_PASSWORD VARCHAR(100),
CONFIRM_PASSWORD VARCHAR(100),
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP
);
