-- CREATE TABLE ACCOUNT

CREATE TABLE "ACCOUNT" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "USERNAME" VARCHAR2(100 BYTE) UNIQUE,
    "PASSWORD_HASH" VARCHAR2(255 BYTE),
    "EMAIL" VARCHAR2(100 BYTE) UNIQUE,
    "FIRST_NAME" VARCHAR2(100 BYTE),
    "LAST_NAME" VARCHAR2(100 BYTE),
    "DATE_OF_BIRTH" TIMESTAMP,
    "ROLE" VARCHAR2(50 BYTE), -- e.g Admin, User, Moderator
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    "LAST_LOGIN" TIMESTAMP
);

COMMIT;