-- CREATE TABLE CARD_GAMES

CREATE TABLE "CARD_GAMES" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "TITLE" VARCHAR2(255 BYTE),
    "DESCRIPTION" CLOB,
    "RELEASE_DATE" TIMESTAMP,
    "GENRE" VARCHAR2(100 BYTE),
    "PLATFORM" VARCHAR2(100 BYTE),
    "IMAGE_URL" CLOB,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);