-- CREATE TABLE NEWS

CREATE TABLE "NEWS" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "TITLE" VARCHAR2(255 BYTE),
    "CONTENT" CLOB,
    "DATE_POSTED" TIMESTAMP,
    "AUTHOR" VARCHAR2(100 BYTE),
    "CATEGORY" VARCHAR2(100 BYTE),
    "IMAGE_URL" CLOB,
    "TAGS" VARCHAR2(255 BYTE),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;