-- CREATE TABLE POINT_SYSTEM

CREATE TABLE "POINT_SYSTEM" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "ACCOUNT_ID" VARCHAR2(255 BYTE),
    "TOURNAMENT_ID" VARCHAR2(255 BYTE),
    "POINTS" NUMBER DEFAULT 0,
    "LAST_UPDATED" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY ("ACCOUNT_ID") REFERENCES "ACCOUNT"("ID")
);