-- CREATE TABLE PRIZES

CREATE TABLE "PRIZES" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "TOURNAMENT_ID" NUMBER,
    "POSITION" NUMBER,
    "DESCRIPTION" CLOB,
    "AMOUNT" NUMBER,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY ("TOURNAMENT_ID") REFERENCES "TOURNAMENT"("ID")
);

CREATE TABLE "PRIZE_POINT" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "POINT_SYSTEM_ID" NUMBER,
    "DESCRIPTION" CLOB,
    "AMOUNT" NUMBER,
    FOREIGN KEY ("PRIZE_ID") REFERENCES "PRIZES"("ID"),
    FOREIGN KEY ("POINT_SYSTEM_ID") REFERENCES "POINT_SYSTEM"("ID")
);