-- CREATE TABLE SHOP

CREATE TABLE SHOP (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    DESCRIPTION TEXT,
    LOCATION VARCHAR(255),
    OWNER VARCHAR(100),
    OPENING_HOURS VARCHAR(100),
    CONTACT_EMAIL VARCHAR(100),
    CONTACT_PHONE VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

CREATE TABLE PRODUCTS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    VENDOR_ID INT,
	NAME VARCHAR (100),
    CODE VARCHAR (100),
    DESCRIPTION BLOB,
    CONDITIONAL VARCHAR (50),
    PRICE INT,
    STOCK_QUANTITY INT,
    IMAGE_URL BLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    FOREIGN KEY (VENDOR_ID) REFERENCES PERSONAL_USER(ID)
);

CREATE TABLE MANAGE_INVENTORY (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT,
    QUANTITY INT,
    LAST_UPDATED TIMESTAMP,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

COMMIT;