-- CREATE TABLE SHOP

CREATE TABLE "SHOP" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "NAME" VARCHAR2(255 BYTE),
    "DESCRIPTION" CLOB,
    "LOCATION" VARCHAR2(255 BYTE),
    "OWNER" VARCHAR2(100 BYTE),
    "OPENING_HOURS" VARCHAR2(100 BYTE),
    "CONTACT_EMAIL" VARCHAR2(100 BYTE),
    "CONTACT_PHONE" VARCHAR2(20 BYTE),
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE "SHOP_ITEMS" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "SHOP_ID" VARCHAR2(255 BYTE),
    "SINGLE_ID" VARCHAR2(255 BYTE),
    "ITEM_NAME" VARCHAR2(255 BYTE),
    "ITEM_DESCRIPTION" CLOB,
    "PRICE" NUMBER,
    "STOCK_QUANTITY" NUMBER,
    "CATEGORY" VARCHAR2(100 BYTE),
    "IMAGE_URL" CLOB,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY ("SHOP_ID") REFERENCES "SHOP"("ID"),
    FOREIGN KEY ("SINGLE_ID") REFERENCES "SINGLE"("ID")
);

COMMIT;