-- CREATE TABLE SINGLES

CREATE TABLE "SINGLES" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "CARD_ID" NUMBER,
     CONSTRAINT "FK_SINGLES_CARD_GAMES" FOREIGN KEY ("CARD_ID") REFERENCES "CARD_GAMES"("ID") ON DELETE CASCADE,
    "TITLE" VARCHAR2(255 BYTE),
    "DESCRIPTION" CLOB, -- e.g Skills, Abilities, Set Info
    "PUBLISHER" VARCHAR2(100 BYTE), -- e.g Zendikar, Booster 12, Promo Pack 
    "RELEASE_DATE" TIMESTAMP,
    "CATEGORY" VARCHAR2(100 BYTE), -- e.g Soccery, Spells, Trainer
    "PLATFORM" VARCHAR2(100 BYTE), -- e.g Pokemon, Yu-Gi-Oh, Magic: The Gathering
    "RARITY" VARCHAR2(255 BYTE),
    "PRICE" NUMBER,
    "STOCK_QUANTITY" NUMBER,
    "IMAGE_URL" CLOB,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;