-- CREATE TABLE TOURNAMENT

CREATE TABLE "TOURNAMENT" (
    "ID" NUMBER PRIMARY KEY AUTOINCREMENT,
    "NAME" VARCHAR2(255 BYTE),
    "DESCRIPTION" CLOB,
    "START_DATE" TIMESTAMP,
    "END_DATE" TIMESTAMP,
    "LOCATION" VARCHAR2(255 BYTE),
    "ENTRY_FEE" NUMBER,
    "PRIZE_POOL" NUMBER,
    "GAME_TITLE" VARCHAR2(255 BYTE),
    "ORGANIZER" VARCHAR2(100 BYTE),
    "RULES" CLOB,
    "REGISTRATION_DEADLINE" TIMESTAMP,
    "MAX_TEAMS" NUMBER,
    "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;