CREATE TABLE TRADE_LISTINGS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_ID INT NOT NULL,
  PRODUCT_ID INT NULL, -- optional link to inventory
  TITLE VARCHAR(255) NOT NULL,
  GAME VARCHAR(50) NOT NULL,
  CONDITION_LABEL VARCHAR(100),
  TYPE ENUM('trade','sale') DEFAULT 'trade',
  WANT_TEXT TEXT,
  NOTES TEXT,
  STATUS ENUM('active','completed','cancelled') DEFAULT 'active',
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (USER_ID),
  INDEX (GAME),
  INDEX (STATUS)
);

CREATE TABLE TRADE_OFFERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  LISTING_ID INT NOT NULL,
  OFFER_USER_ID INT NOT NULL,
  MESSAGE TEXT,
  STATUS ENUM('pending','accepted','rejected') DEFAULT 'pending',
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX (LISTING_ID),
  INDEX (OFFER_USER_ID)
);